name: pizzeria_app
description: App de pizzería con delivery y pagos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  url_launcher: ^6.1.14
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1   # <-- Agregado aquí

flutter:
  uses-material-design: true
  
  # Opcional: agregar assets
  # assets:
  #   - images/logo.png
  
  # Opcional: agregar fuentes personalizadas
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf


flutter_icons:
  android: true     
  ios: true                
  image_path: "assets/icon.png" 
  adaptive_icon_background: "#ffffff" 
  adaptive_icon_foreground: "assets/icon.png"  